env:
  global:
    - CI_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER

script:
  - "👋..."

after_success:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=$(make version)
  - echo "GIT_TAG=$GIT_TAG"
  - eval "$(ssh-agent)"
  - echo "$GITHUB_DEPLOY_KEY" > /tmp/github_deploy_key
  - chmod 600 /tmp/github_deploy_key
  - ssh-add /tmp/github_deploy_key
  - >
    [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ] &&
    git tag $GIT_TAG -f -a -m "Version $GIT_TAG built by Travis CI - https://travis-ci.com/$TRAVIS_REPO_SLUG/jobs/$TRAVIS_JOB_ID"
    || true
  - >
    [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ] &&
    git push -q $GIT_TAG || true